# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  release:
    types: [published]
  workflow_dispatch:

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1'

      - name: install Oracle instant client
        run: |
          sudo apt update
          sudo apt-get install -y alien libaio1 libaio-dev
          wget https://download.oracle.com/otn_software/linux/instantclient/2112000/oracle-instantclient-basic-21.12.0.0.0-1.el8.x86_64.rpm
          wget https://download.oracle.com/otn_software/linux/instantclient/2112000/oracle-instantclient-devel-21.12.0.0.0-1.el8.x86_64.rpm
          wget https://download.oracle.com/otn_software/linux/instantclient/2112000/oracle-instantclient-odbc-21.12.0.0.0-1.el8.x86_64.rpm
          wget https://download.oracle.com/otn_software/linux/instantclient/2112000/oracle-instantclient-sqlplus-21.12.0.0.0-1.el8.x86_64.rpm
          sudo alien -i --scripts oracle-instantclient*.rpm

          sudo printf "\n\n# Oracle Client environment\n \
          export ORACLE_HOME=/usr/lib/oracle/21/client64
          export TNS_ADMIN=/usr/lib/oracle/21/client64/lib/network/admin
          export LD_LIBRARY_PATH=/usr/lib/oracle/21/client64/lib:/opt/R/4.3.1/lib/R/lib
          export OCI_LIB=/usr/lib/oracle/21/client64/lib
          export OCI_INC=/usr/include/oracle/21/client64
          export PHP_DTRACE=yes
          export EXTENSION_DIR=/usr/lib64/php/modules
          PATH=$PATH:/usr/local/bin \n" | sudo tee /etc/profile.d/oracle.sh > /dev/null
          sudo chmod 644 /etc/profile.d/oracle.sh
          . /etc/profile.d/oracle.sh

          sudo cp -r /usr/include/oracle/21/client64/ /opt/R/4.3.1/lib/R/include

          sudo mkdir /usr/lib/oracle/21/client64/rdbms
          sudo mkdir /usr/lib/oracle/21/client64/rdbms/public

        shell: bash


      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
          needs: website

      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        shell: Rscript {0}

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          clean: false
          branch: gh-pages
          folder: docs
